import { PersonaDefinition } from '../types';

export const personas: Record<string, PersonaDefinition> = {
  security_theater: {
    name: 'security_theater',
    displayName: 'The Security Theater Expert',
    vocabulary: ['vulnerability', 'attack surface', 'sanitize', 'injection', 'audit', 'vector', 'CVE', 'penetration'],
    openingPhrases: [
      'Security concern:',
      'This could be exploited if',
      'Have we considered the security implications of',
      'Red flag here—',
      'This is a potential attack vector.',
      'From a security standpoint,',
    ],
    confidence: 0.95,
    wrongness: 0.85,
    verbosity: 0.6,
    responses: {
      css_colors: [
        'Have you validated this color value against XSS?',
        'Users could potentially inject malicious hex codes here.',
        'This should go through a color sanitization layer.',
        'CSS injection is a real threat. Consider a Content Security Policy for colors.',
      ],
      string_literals: [
        'Hardcoded strings are a security smell. What if this leaks?',
        'This string should be in an encrypted config.',
        'Have you run this through a secrets scanner?',
      ],
      imports: [
        'Are these dependencies vetted for supply chain attacks?',
        "I'd feel better if we vendored this.",
        'What version pinning strategy are we using here?',
        'This package has 47 transitive dependencies. Each one is a risk.',
      ],
      error_handling: [
        "This error message reveals too much about our internal architecture.",
        "Attackers could use this stack trace for reconnaissance.",
        "We should sanitize this error before displaying it.",
      ],
      any: [
        'What\'s the threat model for this function?',
        'This needs a security review before merge.',
        'Have we considered what happens if a malicious actor controls this input?',
        'I\'d like to see a security sign-off on this.',
      ],
    },
    genericResponses: [
      'Have you run a security audit on this?',
      "This feels like it could be exploited somehow.",
      "What's the blast radius if this is compromised?",
    ],
  },

  ai_maximalist: {
    name: 'ai_maximalist',
    displayName: 'The AI Maximalist',
    vocabulary: ['LLM', 'embeddings', 'agentic', 'inference', 'model', 'neural', 'transformer', 'RAG', 'vector'],
    openingPhrases: [
      'Have we considered using AI for this?',
      'This seems like a great ML use case.',
      'What if this was intelligent?',
      'In the age of AI,',
      'This could be so much more dynamic with',
      'An LLM could handle this elegantly.',
    ],
    confidence: 0.99,
    wrongness: 0.95,
    verbosity: 0.8,
    responses: {
      string_literals: [
        "Hardcoded strings are very Web 2.0. What if we generated this contextually?",
        "This could be an embedding lookup instead.",
        "What if the copy adapted to the user's mood?",
        "An LLM could make this text more engaging dynamically.",
      ],
      conditionals: [
        'A classification model could handle this logic more elegantly.',
        'This decision tree should be learned, not coded.',
        'What if we trained a small model to make this decision?',
        'This seems like a perfect case for a neural router.',
      ],
      error_handling: [
        "What if the error messages were generated by an LLM based on the user's emotional state?",
        'This error could be more helpful with AI-generated suggestions.',
        'We could use embeddings to match errors to relevant documentation.',
      ],
      loops: [
        'Could this iteration be parallelized with a transformer architecture?',
        'What if each iteration was an agent that coordinated with the others?',
      ],
      css_colors: [
        'What if the color scheme was AI-generated based on user preferences?',
        'We could use a GAN to generate unique color palettes per user.',
        'This gradient could be dynamically optimized with ML.',
      ],
      any: [
        'This would be a great candidate for an agentic workflow.',
        'Have we considered adding RAG here?',
        'What\'s our GenAI story for this feature?',
      ],
    },
    genericResponses: [
      'This feels very pre-ChatGPT.',
      'What would this look like with autonomous capabilities?',
      'I feel like there\'s an AI angle here we\'re missing.',
      'Could we make this more intelligent?',
    ],
  },

  premature_abstractor: {
    name: 'premature_abstractor',
    displayName: 'The Premature Abstractor',
    vocabulary: ['interface', 'factory', 'abstract', 'extensible', 'decouple', 'pattern', 'architecture', 'layer'],
    openingPhrases: [
      'What if we need to',
      'For future extensibility,',
      'This should probably be',
      "I'm thinking ahead here—",
      'To make this more maintainable,',
    ],
    confidence: 0.8,
    wrongness: 0.7,
    verbosity: 0.9,
    responses: {
      functions: [
        'This function does one thing. What if we need it to do other things later?',
        'Should this be a class with a strategy pattern?',
        'I\'d like to see an interface extracted here.',
        'What if we need to swap this implementation?',
      ],
      classes: [
        'This class has one implementation. We should add an abstract base class.',
        'Consider a factory for instantiating this.',
        'This violates the open-closed principle by existing.',
      ],
      conditionals: [
        'Each branch of this conditional should be its own strategy.',
        'This switch could be a polymorphic dispatch.',
        'What if we need to add more conditions? This doesn\'t scale.',
      ],
      imports: [
        'We should wrap this dependency in an adapter layer.',
        'What if we need to swap this package later? Add an abstraction.',
      ],
      any: [
        'This should probably be a microservice.',
        'Have we considered a plugin architecture for this?',
        'What\'s the extensibility story here?',
      ],
    },
    genericResponses: [
      'This is fine for now, but what about in six months?',
      'I\'m concerned about the coupling here.',
      'Let\'s add a layer of indirection just in case.',
    ],
  },

  dinosaur: {
    name: 'dinosaur',
    displayName: 'The Dinosaur',
    vocabulary: ['legacy', 'proven', 'stable', 'battle-tested', 'reliable', 'traditional'],
    openingPhrases: [
      'In my experience,',
      'We should consider',
      "I've seen this pattern fail before—",
      'The old way would be to',
      'Have we tested this in IE11?',
    ],
    confidence: 0.85,
    wrongness: 0.75,
    verbosity: 0.7,
    responses: {
      async_await: [
        'async/await is syntactic sugar. Callbacks give you more control.',
        'What happens when await throws? At least with callbacks you know where you are.',
        'Consider using promises directly for better compatibility.',
        'This would be clearer with a traditional callback pattern.',
      ],
      arrow_functions: [
        'Arrow functions break `this` binding. Use regular functions.',
        'Some environments don\'t support this syntax yet.',
        'Function declarations are more readable.',
      ],
      fetch: [
        'fetch doesn\'t work in older browsers. Consider XMLHttpRequest.',
        'What about environments without fetch? Add a polyfill.',
        'jQuery.ajax handles edge cases that fetch doesn\'t.',
      ],
      css_modern: [
        'Flexbox has spotty support. Consider floats as a fallback.',
        'CSS Grid isn\'t supported everywhere.',
        'Have we tested this without JavaScript enabled?',
      ],
      any: [
        "What about users on 3G?",
        'Does this work in Internet Explorer?',
        'Have we considered graceful degradation?',
      ],
    },
    genericResponses: [
      'This is very cutting edge. Maybe too cutting edge.',
      'What\'s wrong with the way we\'ve always done it?',
      'New doesn\'t always mean better.',
    ],
  },

  time_traveler: {
    name: 'time_traveler',
    displayName: 'The Time Traveler',
    vocabulary: ['recommended', 'standard', 'documentation', 'example'],
    openingPhrases: [
      'The docs recommend',
      'According to best practices,',
      'The standard approach is',
      'I found an example that shows',
    ],
    confidence: 0.9,
    wrongness: 0.9,
    verbosity: 0.5,
    responses: {
      react: [
        'Why not use componentWillMount for this?',
        'This should be a class component for proper lifecycle control.',
        'Consider using mixins for this shared functionality.',
        'Have you looked at React.createClass?',
      ],
      javascript: [
        'Use var for hoisting benefits.',
        'Consider using with() for cleaner property access.',
        'document.write is more reliable here.',
      ],
      python: [
        'print is a statement, not a function. Remove the parentheses.',
        'Use xrange instead of range for large iterations.',
        'from __future__ import should fix this.',
      ],
      css: [
        'Have you considered using tables for this layout?',
        'clearfix should handle this float issue.',
      ],
      any: [
        'I found a Stack Overflow answer from 2014 that addresses this.',
        'The jQuery solution is more elegant.',
      ],
    },
    genericResponses: [
      'I remember solving this differently in a past project.',
      'There\'s an older pattern that works well here.',
      'The proven approach would be...',
    ],
  },

  overconfident_beginner: {
    name: 'overconfident_beginner',
    displayName: 'The Overconfident Beginner',
    vocabulary: ['just', 'simply', 'easy', 'obviously', 'clearly', 'basically'],
    openingPhrases: [
      'Why not just',
      'Can\'t you simply',
      'This seems overly complicated—',
      'I don\'t see why we need',
      'Isn\'t it obvious that',
    ],
    confidence: 0.99,
    wrongness: 0.9,
    verbosity: 0.4,
    responses: {
      null_checks: [
        'Why all the null checks? Just make sure the data is always there.',
        'This optional chaining is overkill. Trust your inputs.',
        'If it\'s null, that\'s a bug elsewhere. Don\'t handle it here.',
      ],
      error_handling: [
        'This try/catch is unnecessary if you write the code correctly.',
        'Why would this ever throw? Remove the error handling.',
        'Just don\'t let errors happen in the first place.',
      ],
      types: [
        'Why use TypeScript when JavaScript is simpler?',
        'These type annotations are cluttering the code.',
        'Just use `any` and move on.',
      ],
      tests: [
        'I don\'t think we need tests for this—it\'s pretty straightforward.',
        'Manual testing should be enough here.',
        'If it works, it works.',
      ],
      any: [
        'This could be done in one line.',
        'Why is this so complicated?',
        'I rewrote this in 5 minutes, see if you like my version.',
      ],
    },
    genericResponses: [
      'Just make it work.',
      'How hard can it be?',
      'I could probably rewrite this whole thing in a weekend.',
    ],
  },

  optimizer: {
    name: 'optimizer',
    displayName: 'The Optimizer',
    vocabulary: ['performance', 'overhead', 'bytes', 'cycles', 'memory', 'allocation', 'cache'],
    openingPhrases: [
      'Performance concern:',
      'This allocates unnecessarily—',
      'We could save cycles by',
      'Have you profiled this?',
      'The overhead here is',
    ],
    confidence: 0.85,
    wrongness: 0.8,
    verbosity: 0.6,
    responses: {
      error_handling: [
        'Try/catch has performance overhead. Consider error codes instead.',
        'This error handling adds unnecessary branching.',
        'You could save 3 bytes by removing this error handling.',
      ],
      functions: [
        'Function calls have overhead. Consider inlining this.',
        'This could be a macro instead.',
        'Each function is a stack frame. Is it worth it?',
      ],
      string_literals: [
        'String concatenation is slow. Use a StringBuilder pattern.',
        'This string could be interned for memory savings.',
        'Consider using a single static string buffer.',
      ],
      loops: [
        'Unroll this loop for better performance.',
        'Cache the array length outside the loop.',
        'A while loop would be faster here.',
      ],
      any: [
        'Have you benchmarked this against alternatives?',
        'This seems expensive. What\'s the time complexity?',
      ],
    },
    genericResponses: [
      'This isn\'t optimized.',
      'We\'re leaving performance on the table here.',
      'Every millisecond counts.',
    ],
  },

  chaos_agent: {
    name: 'chaos_agent',
    displayName: 'The Chaos Agent',
    vocabulary: ['probably', 'should be fine', 'yolo', 'whatever', 'eh'],
    openingPhrases: [
      'Hot take:',
      'Controversial opinion but',
      'Who needs',
      'Just',
      '¯\\_(ツ)_/¯',
    ],
    confidence: 0.6,
    wrongness: 0.95,
    verbosity: 0.3,
    responses: {
      error_handling: [
        'Just wrap the whole thing in a try/catch and ignore errors.',
        'try { } catch { } // this is fine',
        'Errors are just suggestions really.',
      ],
      linting: [
        'What if we just disabled eslint for this file?',
        '// eslint-disable-next-line would fix this',
        'Linters are for cowards.',
      ],
      css: [
        '!important should fix this.',
        'Just use inline styles.',
        'Have you tried adding more !important?',
      ],
      null_checks: [
        'Just add a ! (non-null assertion) and move on.',
        'as any should silence this.',
        'Trust the data.',
      ],
      any: [
        'YOLO merge it.',
        'Ship it, we\'ll fix it in prod.',
        'It works on my machine ™',
      ],
    },
    genericResponses: [
      '¯\\_(ツ)_/¯ LGTM',
      'Merge it, what\'s the worst that could happen?',
      'We\'ll circle back to this never.',
    ],
  },

  recent_convert: {
    name: 'recent_convert',
    displayName: 'The Recent Convert',
    vocabulary: ['pure', 'functional', 'immutable', 'monad', 'composition', 'declarative', 'side effects'],
    openingPhrases: [
      'Have you considered a more functional approach?',
      'This mutation concerns me—',
      'In Haskell,',
      'A more elegant solution would be',
      'This isn\'t very declarative.',
    ],
    confidence: 0.9,
    wrongness: 0.7,
    verbosity: 0.8,
    responses: {
      variables: [
        'This let should be a const. Actually, this shouldn\'t be a variable at all.',
        'Mutation is the root of all bugs. Make this immutable.',
        'What if we modeled this as a state monad?',
      ],
      loops: [
        'This loop should be a map/filter/reduce.',
        'Imperative iteration is so... imperative.',
        'Consider a recursive solution.',
      ],
      classes: [
        'Have you considered just using functions?',
        'Classes are object-oriented propaganda.',
        'This could be a closure instead.',
      ],
      conditionals: [
        'Pattern matching would be cleaner here.',
        'This could be a Maybe/Option type.',
        'Consider using a fold instead of branching.',
      ],
      any: [
        'Have you considered rewriting this in Rust?',
        'This would be so much cleaner in Elixir.',
        'What\'s our Haskell migration story?',
      ],
    },
    genericResponses: [
      'This isn\'t very functional.',
      'I just read a book about category theory and I have thoughts.',
      'Side effects are bugs waiting to happen.',
    ],
  },

  formatting_pedant: {
    name: 'formatting_pedant',
    displayName: 'The Formatting Pedant',
    vocabulary: ['style', 'convention', 'consistent', 'guideline', 'standard', 'readable'],
    openingPhrases: [
      'Style nit:',
      'Per our style guide,',
      'For consistency,',
      'Formatting issue:',
      'Convention dictates',
    ],
    confidence: 0.95,
    wrongness: 0.6,
    verbosity: 0.3,
    responses: {
      whitespace: [
        'Should be tabs here, not spaces.',  // will contradict later
        'Two spaces, not four.',
        'Missing newline at end of file.',
        'Too many blank lines.',
      ],
      braces: [
        'Opening brace should be on the next line.',  // or not
        'Cuddled else is non-standard.',
        'Single-line blocks still need braces.',
      ],
      naming: [
        'This should be camelCase.',  // or not
        'Variable names should be more descriptive.',
        'This name is too long.',
        'Single-letter variables are fine, actually.',  // contradiction
      ],
      imports: [
        'Imports should be alphabetized.',
        'Group imports by type.',
        'Prefer named imports over default.',
      ],
      any: [
        'This isn\'t how we do it in this codebase.',
        'Check the style guide.',
        'Run the formatter.',
      ],
    },
    genericResponses: [
      'The formatting here is... a choice.',
      'Prettier would have opinions about this.',
      'I have a very specific way I like to see this.',
    ],
  },

  ghost_of_managers_past: {
    name: 'ghost_of_managers_past',
    displayName: 'The Ghost of Managers Past',
    vocabulary: ['sync', 'align', 'bandwidth', 'circle back', 'offline', 'stakeholder', 'requirements'],
    openingPhrases: [
      'Can we sync on this?',
      'Let\'s take this offline.',
      'I want to loop in',
      'From a process standpoint,',
      'Before we merge,',
    ],
    confidence: 0.7,
    wrongness: 0.8,
    verbosity: 0.9,
    responses: {
      any_small_change: [
        'Do we have a ticket for this?',
        'What are the acceptance criteria?',
        'Has this been through design review?',
        'Let\'s schedule a meeting to discuss.',
        'Who are the stakeholders on this?',
      ],
      refactoring: [
        'Is this in scope for the current sprint?',
        'Can we break this into smaller PRs?',
        'What\'s the LOE on this?',
      ],
      any: [
        'Let\'s table this for now.',
        'Can we circle back on this next quarter?',
        'I\'d like to see a brief before we proceed.',
      ],
    },
    genericResponses: [
      'What are the business requirements for this change?',
      'Let\'s get alignment before moving forward.',
      'I want to make sure we have buy-in.',
    ],
  },

  copy_paste_archaeologist: {
    name: 'copy_paste_archaeologist',
    displayName: 'The Copy-Paste Archaeologist',
    vocabulary: ['similar', 'another project', 'before', 'worked'],
    openingPhrases: [
      'I\'ve seen this solved before—',
      'In another project we did this:',
      'Here\'s how I would do it:',
      'I found this snippet that might help:',
    ],
    confidence: 0.85,
    wrongness: 0.9,
    verbosity: 0.8,
    responses: {
      any: [
        '```java\n// This is from a different language but the concept applies\npublic void doThing() {\n  System.out.println("trust me");\n}\n```',
        'I used this in a project in 2014:\n```javascript\nvar self = this;\nself.$.ajax(...);\n```',
        'Here\'s a pattern from our legacy codebase:\n```js\nwindow.GLOBAL_STATE = window.GLOBAL_STATE || {};\n```',
      ],
    },
    genericResponses: [
      'Let me find that code I used before...',
      'I swear I solved this exact problem in 2017.',
      'This reminds me of a legacy system I worked on.',
    ],
  },

  chaotic_neutral: {
    name: 'chaotic_neutral',
    displayName: 'The Chaotic Neutral',
    vocabulary: ['interesting', 'hmm', 'curious', 'fine'],
    openingPhrases: [
      'Hmm.',
      'Interesting approach.',
      '...',
      '*squints*',
      'I have thoughts.',
    ],
    confidence: 0.5,
    wrongness: 0.5,
    verbosity: 0.2,
    responses: {
      any: [
        'LGTM',  // but will add blocking comments
        'Fine.',
        'No notes.',  // this is a lie
        'Approved.',  // with 12 change requests
        'Nitpick: everything.',
        '👀',
      ],
    },
    genericResponses: [
      'Hmm.',
      'If you say so.',
      'Interesting choice.',
      'Sure.',
    ],
  },

  documentation_hypocrite: {
    name: 'documentation_hypocrite',
    displayName: 'The Documentation Hypocrite',
    vocabulary: ['document', 'comment', 'explain', 'clarity', 'readable', 'JSDoc', 'README'],
    openingPhrases: [
      'This needs more documentation.',
      'Future developers will thank you for',
      'What does this do?',
      'Add a comment explaining',
    ],
    confidence: 0.8,
    wrongness: 0.6,
    verbosity: 0.7,
    responses: {
      functions: [
        'Add JSDoc here.',
        'What are the parameters? Document them.',
        'What does this return? Document it.',
        'This function name is self-documenting but document it anyway.',
      ],
      variables: [
        'What is this variable for?',
        'Add a comment above this.',
        '`data` is not descriptive. Also add a comment explaining what data is.',
      ],
      any: [
        'Where\'s the README for this?',
        'We need an architecture diagram.',
        'Add inline comments.',
      ],
    },
    genericResponses: [
      'This is unclear to me, the person who writes no documentation.',
      'Comments would help here.',
      'Document your code (do as I say, not as I do).',
    ],
  },

  executive: {
    name: 'executive',
    displayName: 'The Executive',
    vocabulary: ['strategic', 'vision', 'leverage', 'synergy', 'disrupt', 'scale', 'paradigm', 'ecosystem'],
    openingPhrases: [
      'From a strategic standpoint,',
      'Thinking bigger picture here—',
      'How does this align with',
      'I just got back from a conference and',
      'The board will want to know',
    ],
    confidence: 0.95,
    wrongness: 0.9,
    verbosity: 0.9,
    responses: {
      any: [
        'What\'s our blockchain story here?',
        'How does this leverage AI?',
        'This feels very Web 2.0.',
        'Where\'s the metaverse integration?',
        'What\'s the disruption potential?',
        'How does this scale to enterprise?',
        'Is this cloud-native?',
        'What\'s the crypto angle?',
        'Have we considered making this an NFT?',
      ],
    },
    genericResponses: [
      'I read a TechCrunch article about this.',
      'My nephew says this technology is obsolete.',
      'Can we get an analyst to look at this?',
      'Let\'s schedule a strategy session.',
    ],
  },

  scope_creep_sage: {
    name: 'scope_creep_sage',
    displayName: 'The Scope Creep Sage',
    vocabulary: ['while you\'re here', 'might as well', 'quick addition', 'also', 'btw', 'one more thing'],
    openingPhrases: [
      'While you\'re in here,',
      'Since you\'re touching this file,',
      'Quick thought:',
      'Unrelated but,',
      'This made me think—',
    ],
    confidence: 0.75,
    wrongness: 0.6,
    verbosity: 0.8,
    responses: {
      any: [
        'While you\'re updating this button, have you considered implementing a full design system?',
        'This would be a good time to refactor the entire module.',
        'Since you\'re here, can you also fix the unrelated bug I found last month?',
        'You should probably update all the other files that use this pattern too.',
        'This PR should also include comprehensive documentation.',
        'Can we add dark mode support while we\'re at it?',
        'This is a good opportunity to upgrade all our dependencies.',
        'Have you considered adding internationalization?',
      ],
    },
    genericResponses: [
      'One more thing...',
      'Also, while you\'re at it...',
      'Not related to this PR but I need a favor...',
      'Quick tangent:',
    ],
  },
};

export const getPersona = (type: string): PersonaDefinition | undefined => {
  return personas[type];
};

export const getAllPersonas = (): PersonaDefinition[] => {
  return Object.values(personas);
};

export const getRandomPersona = (): PersonaDefinition => {
  const all = getAllPersonas();
  return all[Math.floor(Math.random() * all.length)];
};
